### ISSUE TITLE
Creating a dummy table Hg1011

### ISSUE THREAD

**Issue by AbhishekVarghese** [AbhishekVarghese/Railway_Resthouse_Management#2]
Himali create a Dummy table in text file to show the format of your sql database

**Comment by hg1211** [comment]
[tableformat.txt](https://github.com/AbhishekVarghese/Railway_Restroom_Management/files/1808180/tableformat.txt)

`

**Comment by AbhishekVarghese** [comment]
GIve it as a pR, to the repo

**Comment by AbhishekVarghese** [comment]
And do all your changes in your Branch and give a Pull req, The one you created Hg1011-patch-1
